services:
  - type: web
    name: pos-backend
    env: node
    runtime: node
    plan: free
    region: singapore
    rootDir: pos-backend
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: RAZORPAY_WEBHOOK_SECRET
        sync: false

  - type: static
    name: pos-frontend
    runtime: static
    plan: free
    region: singapore
    rootDir: pos-frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_BACKEND_URL
        fromService:
          type: web
          name: pos-backend
          property: host
      - key: VITE_SOCKET_URL
        fromService:
          type: web
          name: pos-backend
          property: host
